#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - i3Config/get_packages
# Started On        - Sat 11 May 14:57:13 BST 2019
# Last Change       - Sat 11 May 17:10:11 BST 2019
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

XERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; exit 1; }

#[ $UID -eq 0 ] || XERR "$LINENO" "Root access is required."

[ -x '/usr/bin/dpkg' ] || XERR "$LINENO" "Dependency '/usr/bin/dpkg' not met."
[ -x '/usr/bin/apt-get' ] || XERR "$LINENO" "Dependency '/usr/bin/apt-get' not met."

PKGS=(
	libanyevent-i3-perl:"Used|in|Perl|script|'dev_setup',|for|i3-wm."
	libnotify-bin:"Contains|the|'notify-send'|notification|binary."
	libnotify4:"Shared|library|for|sending|notifications|to|a|daemon."
	compton:"For|excellent|X11|compositing,|based|on|'xcompmgr'."
	dunst:"A|lightweight|and|highly-configurable|notifications|daemon."
	feh:"Terminal|program|to|display|images|and|set|the|background|image."
	firefox:"A|standard|of|a|web|browser;|old,|but|wise|and|evolved."
	i3-wm:"Window|manager|on|which|the|TFL|'i3Config'|repository|is|based."
	i3lock:"Simple,|configurable|screen|locker,|used|by|'~/.i3a/lockscreen'."
	imagemagick:"A|full|suite|of|image|manipulation|programs."
	keynav:"Keynav|makes|your|keyboard|a|fast|mouse|cursor|mover."
	moc:"MOC|(Music|on|Console)|is|a|full-screen|audio|player."
	mplay:"MOC|Wrapper|for|a|clean|layout|with|a|subtle|transparent|theme."
	procps:"A|set|of|utilities|for|the|'/proc'|FS;|mainly|used|for|'pkill'."
	pulseaudio:"PulseAudio|is|a|sound|server|for|POSIX|and|WIN32|systems."
	pulseaudio-utils:"Command|line|tools|for|the|PulseAudio|sound|server."
	redshift:"Adjusts|the|color|temperature|of|your|screen;|used|by|redshifter."
	scrot:"Command|line|screen-|window-|or|selection-shooter."
	sound-theme-freedesktop:"Various|audio|files|used|in|this|i3-wm|setup."
	suckless-tools:"Provides|the|lightweight|'dmenu',|which|this|setup|uses."
	x11-utils:"Package|is|needed|for|various|X11|tools|it|provides."
	x11-xkb-utils:"Tools|in|this|package|are|needed|in|'~/.i3a/initialise'."
	x11-xserver-utils:"Tools|in|this|package|are|needed|in|'~/.i3a/initialise'."
	xfce4-terminal:"The|terminal|used|in|this|setup,|in|a|few|ways."
	yad:"Used|to|display|a|simple|logout|GUI|which|runs|'pkill|-u|\$USER'."
)

INFO(){ printf "\n%s: %s\n" "$1" "$2"; }

APT_OPTS='-q -o Dpkg::Progress=true -o Dpkg::Progress-Fancy=true -o '
APT_OPTS+='APT::Get::AutomaticRemove=true -o APT::Get::Purge=true'

# In a loop intentionally, for chance to prompt at each package.
for I in ${PKGS[@]}; {
	read I <<< "${I//|/ }"
	INFO "${I%%:*}" "${I#*:}"
	/usr/bin/apt-get $APT_OPTS install "${I%%:*}"
	read -n 1 -s -p 'Press any key to continue... '
	printf "\n"
}
