#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - $HOME/.flout/avgcpuusage
# Started On        - Thu  8 Feb 00:07:39 GMT 2018
# Last Change       - Thu  8 Feb 21:19:06 GMT 2018
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

while read -a X; do
	if [ "$A" == "true" ]; then
		declare -i S=0
		for V in ${X[0]} ${X[1]} ${X[2]} ${X[3]} ${X[4]}; {
			P="${V/.}"
			S+=$P
		}

		B=${S/*.}

		if [ $B -gt 50 ]; then
			S=$((${S%??}+1))
		elif [ $B -lt 50 ]; then
			S=$((${S%??}-1))
		fi

		printf "%3d%%\n" "$S"
		break
	else
		[ "${X[0]}" == "avg-cpu:" ] && A="true"
	fi
done <<< "$(/usr/bin/iostat -c)"
