#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - $HOME/.flout/countdown
# Started On        - Thu  8 Feb 00:09:41 GMT 2018
# Last Change       - Thu  8 Feb 00:45:39 GMT 2018
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------
# Displays a countdown for the given target.
#
# SYNTAX:             countdown [TARGET]
#----------------------------------------------------------------------------------

printf -v NOW "%(%F)T\n" "-1"
RESULT=$((`/bin/date -d "$1" +%s` - `printf '%(%s)T'`))
printf "%'${CD_PAD}d" "$RESULT"

unset NOW CD_TARGET RESULT CD_PAD
