#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - i3config/.flout/freestorage
# Started On        - Sun  4 Feb 20:00:09 GMT 2018
# Last Change       - Thu  8 Feb 00:48:32 GMT 2018
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------
# Display the device $1's available amount of storage space, in MB/MiB.
#
# SYNTAX:             freestorage [DEV]
#----------------------------------------------------------------------------------

while read -a X; do
	if [ "${X[0]}" == "$1" ]; then
		printf "%'7dM\n" "${X[3]}"
	fi
done <<< "$(/bin/df -m)"

unset X
