#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - $HOME/.flout/githubfollows
# Started On        - Tue  6 Feb 20:21:00 GMT 2018
# Last Change       - Thu  8 Feb 00:51:35 GMT 2018
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------
# Output the current number of followers the target account has.
#
# SYNTAX:             githubfollows [URL]
#----------------------------------------------------------------------------------

read -a FETCH <<< "$(
	while read LINE; do
		#TODO - This is probably unreliable, but it's something. Revise?
		[[ "$LINE" =~ ^[0-9]+$ ]] && printf "%d " "${LINE//[!0-9]}"
	done <<< "$(/usr/bin/wget -q "$1" -O -)"
)"

printf "%2d" "${FETCH[2]}"

unset LINE FETCH
