#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - i3config/.flout/kernlatest-stable
# Started On        - Mon  5 Feb 17:32:18 GMT 2018
# Last Change       - Mon  5 Feb 17:39:25 GMT 2018
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------
# Display the latest stable kernel version.
#----------------------------------------------------------------------------------

KERN_URL="https://www.kernel.org/"

while read -a LINE; do
	[ "${LINE[0]}" == \<td\>stable:\</td\> ] && CORRECT="true"

	if [ "$CORRECT" == "true" ]; then
		if [[ "${LINE[@]}" =~ \<strong\>[0-9]+\.[0-9]+\.[0-9]+\</strong\> ]]; then	
			printf "%s\n" "${LINE[@]}"
			break
		fi
	fi
done <<< "$(/usr/bin/wget -q "$KERN_URL" -O -)"
