#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - $HOME/.flout/kernelcheck
# Started On        - Thu  8 Feb 00:05:38 GMT 2018
# Last Change       - Thu  8 Feb 00:05:48 GMT 2018
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

K="/proc/sys/kernel/osrelease"
[ -f "$K" -a -r "$K" ] && printf "%19s" "`< $K`"

unset K
