#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - $HOME/.flout/mountcount
# Started On        - Wed  7 Feb 23:50:30 GMT 2018
# Last Change       - Wed  7 Feb 23:57:49 GMT 2018
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------
# Display the total number of mounted devices at /dev/*.
#----------------------------------------------------------------------------------

declare -i C=0
while read -a X; do
	[[ "${X[0]}" == /dev/* ]] && C+=1
done < /proc/mounts

printf "%2d" "$C"

unset C X
