#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - $HOME/.flout/openfiles
# Started On        - Wed  7 Feb 23:51:59 GMT 2018
# Last Change       - Wed  7 Feb 23:58:29 GMT 2018
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------
# Output the total number of opened files under the current user.
#----------------------------------------------------------------------------------

readarray X <<< "$(/usr/bin/lsof -t -u $UID 2> /dev/null)"
printf "%3d" "${#X[@]}"

unset X
