#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - $HOME/.flout/terminals
# Started On        - Wed  7 Feb 23:18:42 GMT 2018
# Last Change       - Thu  8 Feb 00:00:11 GMT 2018
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------
# Output the total number of TERMINAL processes.
#----------------------------------------------------------------------------------

TERMINAL="terminology"

read -a X <<< `/bin/pidof "$TERMINAL"`
printf "%2d" "${#X[@]}"

unset X
