#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - i3config/.flout/timedate
# Started On        - Sun  4 Feb 20:00:09 GMT 2018
# Last Change       - Sun  4 Feb 20:42:11 GMT 2018
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------
# Display the currently available RAM, in MB/MiB.
#----------------------------------------------------------------------------------

printf "%(%X (%F))T" "-1"
