#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - i3config/.flout/totalram
# Started On        - Sun  4 Feb 20:00:09 GMT 2018
# Last Change       - Sun  4 Feb 20:43:15 GMT 2018
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------
# Display the total RAM in the system, as read by the free command, in MB/MiB.
#----------------------------------------------------------------------------------

while read -a X; do
	if [ "${X[0]}" == "Mem:" ]; then
		printf "%'6dM\n" "${X[1]}"
	fi
done <<< "$(/usr/bin/free -m)"

unset X
