#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - $HOME/.flout/uptime
# Started On        - Wed  7 Feb 23:53:12 GMT 2018
# Last Change       - Thu  8 Feb 00:00:43 GMT 2018
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------
# Display the current session uptime.
#----------------------------------------------------------------------------------

while read -a X; do
	if [ "${X[1]}" == "up" ]; then
		printf "%3d\n" "${X[2]%,}"
		break
	fi
done <<< "$(/usr/bin/uptime)"

unset X
