#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - $HOME/.flout/usbcount
# Started On        - Wed  7 Feb 23:21:33 GMT 2018
# Last Change       - Thu  8 Feb 00:00:57 GMT 2018
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------
# Output the total number of USB devices detected, including hubs.
#----------------------------------------------------------------------------------

readarray X <<< "$(/usr/bin/lsusb)"
printf "%2d\n" "${#X[@]}"

unset X
