#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - i3config/.flout/usercountunique
# Started On        - Sun  4 Feb 20:00:09 GMT 2018
# Last Change       - Sun  4 Feb 21:03:31 GMT 2018
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------
# Display the current number of users logged in. (shouldn't contain duplicates)
#----------------------------------------------------------------------------------

declare -i C=0
while read X; do
	if [ "x$O" == "x$X" ]; then
		continue
	else
		C+=1
		O="$X"
	fi
done <<< `/usr/bin/users`
printf "%2d" "$C"

unset X C O
