#!/usr/bin/env bash

#------------------------------------------------------------------------------
# Project Name      - i3Config/source/.i3a/comp_toggle
# Started On        - Sun  3 Jan 05:14:26 GMT 2021
# Last Change       - Wed 16 Mar 22:41:57 GMT 2022
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------

# picom | compton
Which='picom'

type -P $Which &> /dev/null || exit $?

ps -C $Which &> /dev/null && Result='Activated'
if [[ $Result == Activated ]]; then
	pkill $Which
else
	$Which -b
fi
