#!/usr/bin/env bash

#------------------------------------------------------------------------------
# Project Name      - i3Config/source/.i3a/compton_toggle
# Started On        - Sun  3 Jan 05:14:26 GMT 2021
# Last Change       - Sun  3 Jan 05:16:50 GMT 2021
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------

type -P compton &> /dev/null || exit $?

ps -C compton &> /dev/null && Result='Activated'
if [ "$Result" == 'Activated' ]; then
	pkill compton
else
	compton -b
fi
