#!/usr/bin/env perl

#------------------------------------------------------------------------------
# Project Name      - i3Config/source/.i3a/dmesg_overflow
# Started On        - Sun  5 Nov 12:04:09 GMT 2017
# Last Change       - Wed 11 Nov 16:49:22 GMT 2020
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# Puts a plaster on the issue of excessive and problematic `dmesg` errors sent
# to `~/.xsession_errors`, this Perl script will remove the file if they're
# found. It's a dirty solution, but beats `dmesg` being a free-for-all.
#
# Dependencies:
#
#    libtfl-perl (>= 2020-01-02)
#------------------------------------------------------------------------------

use strict;
use warnings;
use autodie;

no warnings 'uninitialized';

my $ProcFile = '/proc/sys/kernel/dmesg_restrict';

if (not -f -r -w $ProcFile){
	die("File '/proc/.../dmesg_restrict' missing or inaccessible")
}elsif ($< != 0){
	die("Root privileges required for system-wide changes")
}

open(my $FH, '<', $ProcFile);
my $Result = <$FH>;
close($FH);

exit(0) if $Result == 1;

my $ErrMSG = 'dmesg: read kernel buffer failed: Operation not permitted';
my $LogFile = $ENV{HOME} . '/.xsession-errors';
if (-f -r $LogFile){
	open(my $FH, '<', $LogFile);

	my $DoDelete;
	while (<$FH>){
		chomp($_);

		if ($_ eq $ErrMSG and -w $LogFile){
			$DoDelete = 'true';
			last
		}
	}

	if ($DoDelete eq 'true'){
		close($FH);
		unlink($LogFile)
	}
}
