#!/bin/sh

#----------------------------------------------------------------------------------
# Project Name      - i3Config/source/.i3a/drop_terminal
# Started On        - Sat 23 Sep 14:47:51 BST 2017
# Last Change       - Tue 17 Dec 23:55:04 GMT 2019
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------
# Allows the user to launch a drop-down terminal, such as guake, tilda, or
# xfce4-terminal's own built-in drop-down feature.
#----------------------------------------------------------------------------------

Sound5='/usr/share/sounds/freedesktop/stereo/dialog-information.oga'
paplay --volume 40000 "$Sound5" & xfce4-terminal --fullscreen --drop-down
