#!/bin/sh

#------------------------------------------------------------------------------
# Project Name      - i3Config/source/.i3a/hush_the_mic
# Started On        - Sun 11 Feb 12:38:53 GMT 2018
# Last Change       - Sat  1 Feb 01:19:44 GMT 2020
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# Gradually decrease the microphone volume. This small script will make use of
# PulseAudio, via pactl. Steals code from: i3config/.i3a/source_lower
#------------------------------------------------------------------------------

Master='alsa_input.usb-Burr-Brown_from_TI_USB_Audio_CODEC-00.analog-stereo'

while :; do
	pacmd list-sources | while read CurLine F1 _ F3 _; do
		if [ "$F1" = 'volume:' ]; then
			if ! [ "$First" = 'true' ]; then
				First="true"
				continue
			fi

			[ $F3 -eq 0 ] && exit 0
		fi

	done

	pactl set-source-volume "$Master" -150

	sleep 0.2
done

