#!/usr/bin/env bash

#------------------------------------------------------------------------------
# Project Name      - i3Config/source/.i3a/initialize
# Started On        - Sat 23 Sep 14:47:51 BST 2017
# Last Change       - Mon 11 Apr 02:49:44 BST 2022
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# Similar code to that found within `.xinitrc` and the like.
#------------------------------------------------------------------------------

DepChk() {
	for Dep in "$@"; do
		if ! type -P &> /dev/null; then
			printf "Err: Dependency '%s' not met.\n" "$Dep" 1>&2
			(( DepCount++ ))
		fi
	done

	(( DepCount > 0 )) && exit 1
}

BG="$HOME/Pictures/Surface Texture with Logo.jpg"

DepChk xmodmap dunst compton redshift redshifter

xmodmap -e 'keysym Caps_Lock = ' &
dunst -config "$HOME/.config/dunst/dunstrc" &
compton --config "$HOME/.config/compton.conf" -b &
redshift -O `redshifter show`K &

case $HOSTNAME in
	Z11)
		DepChk xset bluetoothctl xset feh mocp

		xset s off -dpms r rate 170 70 &

		# Make sure bluetooth is available right out of the gate. Without
		# this, Bluetooth isn't enabled and so the headsets don't connect.
		bluetoothctl <<-EOF &
			power on
			discoverable off
			exit
		EOF

		feh --no-fehbg --bg-scale "$BG" &
		mocp -S &
		nwchk -I -N enp3s0 &

		File="$HOME/bin/autorun"
		[[ -f $File && -x $File ]] && "$File" ;;
	Sam)
		DepChk xset xset feh

		xset s off r rate 180 60 &
		feh --bg-center "$BG" & ;;
esac
