#!/usr/bin/env bash

#----------------------------------------------------------------------------------
# Project Name      - i3Config/source/.i3a/leave_session
# Started On        - Wed  1 Nov 00:50:35 GMT 2017
# Last Change       - Mon 13 May 01:09:44 BST 2019
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------
# Log out of your system with this simple interactive graphical prompt, using yad.
#----------------------------------------------------------------------------------

yad --center --title="Session Logout" --borders=7\
	--on-top --text="Log out of the current session?"

if [ $? -eq 0 ]; then
	pkill -u $USER
fi

