#!/bin/sh

#----------------------------------------------------------------------------------
# Project Name      - i3Config/source/.i3a/leave_session
# Started On        - Wed  1 Nov 00:50:35 GMT 2017
# Last Change       - Thu 12 Dec 03:17:50 GMT 2019
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

. /usr/lib/tflbp-sh/ChkDep

ChkDep notify-send id pkill hostname sleep sync

HOSTNAME=`hostname`
USER=`id -un`

sync

Message="ALERT: Logging out user '$USER' from '$HOSTNAME' in 10s..."
notify-send --urgency=critical "$Message"

sleep 10s

pkill -u "$USER"
