#!/usr/bin/env bash

#----------------------------------------------------------------------------------
# Project Name      - i3Config/source/.i3a/lockscreen
# Started On        - Thu  4 Apr 12:38:37 BST 2019
# Last Change       - Wed 27 Nov 00:21:09 GMT 2019
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

#TODO - If the lock key is held, multiple instances of this script are executed.

set -o errexit

FILE="$(mktemp -u --suffix='_lock.png')"
SOUND03="/usr/share/sounds/freedesktop/stereo/network-connectivity-lost.oga"
SOUND04="/usr/share/sounds/freedesktop/stereo/network-connectivity-established.oga"

DoTrap(){ rm -f "$FILE"; }

trap DoTrap EXIT

TEMPSOUND="$HOME/Documents/Sound Files/Sound Effects/button-24.wav"

scrot -z "$FILE"
convert "$FILE" -gaussian-blur 8x8 "$FILE"
paplay --volume 40000 "$SOUND03" &
i3lock -u -n -i "$FILE"
paplay --volume 40000 "$SOUND04" &
