#!/bin/sh

#------------------------------------------------------------------------------
# Project Name      - i3Config/source/.i3a/partmount
# Started On        - Mon 15 Jan 20:17:34 GMT 2018
# Last Change       - Wed 11 Nov 16:54:21 GMT 2020
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# This will not work on systems without open policies for udisksctl(1), such as
# the default installation of Ubuntu 18.04. This can be solved by installing
# the `policykit-desktop-privileges` package.
#
# SYNTAX:    partmount [OPTS]
#
# ARGS:      --uuid|-U UUID    - Where UUID is one of the filesystem to mount.
#            --label|-L LABEL  - Where LABEL is one of the filesystem to mount.
#            --name|-N NAME    - Where NAME is one of the filesystem to mount.
#
# NOTE:      NAME is the block device name. (`/dev/sda1` | `sda1`)
#
# Dependencies:
#
#   notify-send(1)
#   udisksctl(1)
#------------------------------------------------------------------------------

Mounter(){
	Noti(){ notify-send --urgency=critical "$1"; }
	if [ -e "$1" ]; then
		udisksctl mount -b "$1" 2> /dev/null && exit 0
		if ! udisksctl unmount -b "$1" 2> /dev/null; then
			Noti 'Unable to unmount file system.'
			exit 1
		fi
	else
		Noti "Chosen $2 invalid or unavailable."
		exit 1
	fi
}

while [ "$1" ]; do
	case $1 in
		--uuid|-U)
			shift; Mounter "/dev/disk/by-uuid/$1" 'UUID' ;;
		--label|-L)
			# All spaces must be replaced with literally '\x20'.
			shift; Mounter "/dev/disk/by-label/$1" 'label' ;;
		--name|-N)
			shift; Mounter "/dev/${1#/dev/}" 'name' ;;
	esac
	shift
done
