#!/bin/sh

#------------------------------------------------------------------------------
# Project Name      - i3Config/source/.i3a/scrot_take
# Started On        - Sat 23 Sep 14:47:51 BST 2017
# Last Change       - Tue 10 Mar 00:37:02 GMT 2020
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# Take a screenshot of the entire screen, using scrot. This is the expected
# behavior of the PrtSc button the keyboard, if configured as such.
#------------------------------------------------------------------------------

FileName="$HOME/Desktop/Screenshot_`date '+%F_%X'`.jpg"

# So stupid, but need this because of `date` being too slow, I think.
sleep 0.1

scrot -zq 100 "$FileName" && notify-send 'Screenshot taken and saved.'
