#!/usr/bin/env bash

#----------------------------------------------------------------------------------
# Project Name      - i3Config/source/.i3a/scrot_win_take
# Started On        - Fri 27 Oct 14:55:25 BST 2017
# Last Change       - Wed 18 Dec 00:47:54 GMT 2019
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------
# Take a screenshot of just the currently active window, with scrot.
#----------------------------------------------------------------------------------

FileName="$HOME/Desktop/Windowshot_`date '+%F_%X'`.jpg"
scrot -u -zq 75 "$FILENAME" && notify-send 'Windowshot taken and saved.'
