#!/bin/sh

#----------------------------------------------------------------------------------
# Project Name      - i3Config/source/.i3a/scrot_win_take
# Started On        - Fri 27 Oct 14:55:25 BST 2017
# Last Change       - Fri 10 Jan 20:11:27 GMT 2020
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------
# Take a screenshot of just the currently active window, with scrot.
#----------------------------------------------------------------------------------

FileName="$HOME/Desktop/Windowshot_`date '+%F_%X'`.jpg"
scrot -zuq 75 "$FILENAME" && notify-send 'Windowshot taken and saved.'
