#!/usr/bin/env bash

#----------------------------------------------------------------------------------
# Project Name      - i3Config/source/.i3a/scrot_take
# Started On        - Sat 23 Sep 14:47:51 BST 2017
# Last Change       - Mon 13 May 01:13:44 BST 2019
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------
# Take a screenshot of the entire screen, using scrot. This is the expected
# behavior of the PrtSc button the keyboard, if configured as such.
#----------------------------------------------------------------------------------

umask 0077

printf -v FILENAME "$HOME/Desktop/Screenshot_%(%F_%X)T.jpg"
SOUND03="/usr/share/sounds/freedesktop/stereo/screen-capture.oga"
if scrot -zq 75 "$FILENAME"; then
	paplay --volume 40000 "$SOUND03"
fi

