#!/bin/sh

#----------------------------------------------------------------------------------
# Project Name      - i3Config/source/.i3a/scrot_sel_take
# Started On        - Sat 23 Sep 14:47:51 BST 2017
# Last Change       - Wed 18 Dec 00:46:48 GMT 2019
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------
# Take a screenshot of the user-selected square region, using scrot.
#----------------------------------------------------------------------------------

FileName="$HOME/Desktop/Selectshot_`date '+%F_%X'`.jpg"
scrot -zsq 75 -d 1 "$FileName" && notify-send 'Selectshot taken and saved.'
