#!/usr/bin/env bash

#------------------------------------------------------------------------------
# Project Name      - i3Config/source/.i3a/shooter
# Started On        - Fri 27 Oct 14:55:25 BST 2017
# Last Change       - Sun 15 Oct 16:44:18 BST 2023
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# Take a screen-, selection-, or window-shot with scrot(1).
#------------------------------------------------------------------------------

Take() {
	local Type=$1
	shift

	if "$@"; then
		notify-send "$Type taken and saved."
	else
		notify-send -u 'critical' "Failed to take ${Type,}."
	fi
}

case $1 in
	--window|-w)
		printf -v File '%s/Desktop/Windowshot_%(%F_%X)T.jpg' "$HOME" -1
		Take Windowshot scrot -zuq 100 "$File" ;;
	--select|-s)
		printf -v File '%s/Desktop/Selectshot_%(%F_%X)T.jpg' "$HOME" -1
		sleep 0.2 # <-- For some reason needed, else scrot(1) fails.
		Take Selectshot scrot -zsq 100 -d 1 "$File" ;;
	'')
		printf -v File '%s/Desktop/Screenshot_%(%F_%X)T.jpg' "$HOME" -1
		Take Screenshot scrot -zq 100 "$File" ;;
	*)
		printf 'Err: Invalid argument(s)\n' 1>&2
		exit 1 ;;
esac
