#!/usr/bin/env bash

#----------------------------------------------------------------------------------
# Project Name      - $HOME/.i3a/sink_mute
# Started On        - Sun 24 Sep 00:30:17 BST 2017
# Last Change       - Mon 13 May 01:14:57 BST 2019
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

if type -fP pactl pacmd > /dev/null 2>&1; then
	while IFS=":" read -a X; do
		[ "${X[0]}" == "Default sink name" ] && MASTER="${X[1]## }"
	done <<< "$(pacmd info)"

	pactl set-sink-mute "$MASTER" toggle
fi

