#!/usr/bin/env bash

#------------------------------------------------------------------------------
# Project Name      - i3Config/source/.i3a/sink_switch
# Started On        - Sun 24 Sep 00:30:17 BST 2017
# Last Change       - Fri 28 Apr 20:28:25 BST 2023
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# This script is more of a personal one than any of the others. I have two
# devices I switch between the mixer and the monitor's speakers. Headphones on
# the former.
#
#TODO:  On 2023-04-28, I've found this doesn't seem to work anymore.
#
#       I use a Bluetooth headset, but even changing `$Dev_1` to the correct
#       string won't yield any serviceable results. Also, the monitor profile
#       is apparently unplugged, so I tried `out:hdmi-stereo`, which is
#       correct, but still, nothing seems to switch over. Apparently my
#       Bluetooth headset doesn't have a profile, according to the pactl(1)
#       output, despite it clearly showing the A2DP Sink profile in
#       pavucontrol(1).
#------------------------------------------------------------------------------

Dev_1='alsa_output.usb-Burr-Brown_from_TI_USB_Audio_CODEC-00.analog-stereo'
Dev_2='alsa_card.pci-0000_01_00.1.hdmi-stereo-extra1'

if type -P pacmd &> /dev/null; then
	while IFS=':' read -a Line; do
		[[ ${Line[0]} == 'Default sink name' ]] && Master=${Line[1]## }
	done <<< "$(pacmd info)"

	if type -P pactl &> /dev/null; then
		if [[ $Master == $Dev_1 ]]; then
			pactl set-card-profile "${Dev_2%.*}" output:hdmi-stereo-extra1
		else
			pactl set-card-profile "${Dev_2%.*}" off
		fi
	fi
fi
