#!/usr/bin/env bash

#------------------------------------------------------------------------------
# Project Name      - i3Config/source/.i3a/sink_lower
# Started On        - Sun 24 Sep 00:30:17 BST 2017
# Last Change       - Tue  3 Mar 16:17:30 GMT 2020
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------

if type -fP pacmd 1> /dev/null 2>&1; then
	while IFS=':' read -a X; do
		[ "${X[0]}" == 'Default sink name' ] && Master=${X[1]## }
	done <<< "$(pacmd info)"

	while read -a X; do
		if [ "$IsMaster" == 'True' ] && [[ ${X[0]} == *volume:* ]]; then
			printf -v Vol '%d' "${X[4]%\%}"
			[ $Vol -le 0 ] && exit 0 || break
		elif [ "${X[0]}" == 'name:' -a "${X[1]//[<>]/}" == "$Master" ]; then
			IsMaster='True'
		fi
	done <<< "$(pacmd list-sinks)"

	if type -fP pactl 1> /dev/null 2>&1; then
		pactl play-sample x11-volume-change & disown
		pactl set-sink-volume "$Master" -500
	fi

	if type -fP pkill 1> /dev/null 2>&1; then
		# Use 'signal=1' and 'interval=once' in the i3blocks configuration
		# file, in order to have this update only when needed.
		pkill -RTMIN+1 i3blocks
	fi
fi

