#!/usr/bin/env bash

#------------------------------------------------------------------------------
# Project Name      - i3Config/source/.i3a/sink_raise
# Started On        - Sun 24 Sep 00:30:17 BST 2017
# Last Change       - Mon 12 Jun 02:10:31 BST 2023
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------

TargetDev='<bluez_sink.B0_18_6F_0B_53_D6.a2dp_sink>'

LimitInt=65536

while read; do
	if [[ $TargetFound == True && $REPLY == +([[:space:]])volume:* ]]; then
		for Field in $REPLY; {
			(( ++FieldNr == 3 )) || continue

			if (( Field + 500 > LimitInt )); then
				pactl set-sink-volume '@DEFAULT_SINK@' $LimitInt
			elif (( Field < LimitInt )); then
				pactl set-sink-volume '@DEFAULT_SINK@' +500
			fi

			exit 0
		}
	elif [[ $REPLY == *"$TargetDev"* ]]; then
		TargetFound='True'
	fi
done <<< "$(pacmd list-sinks)"
