#!/bin/sh

#------------------------------------------------------------------------------
# Project Name      - i3Config/source/.i3a/sink_mute
# Started On        - Sun 24 Sep 00:30:17 BST 2017
# Last Change       - Tue  3 Mar 15:12:45 GMT 2020
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# Toggle mute the default sink (output) audio device.
#------------------------------------------------------------------------------

pacmd info | while IFS=':' read Key Value; do
	if [ "$Key" = 'Default sink name' ]; then
		pactl set-sink-mute "${Value## }" toggle
	fi
done
