#!/usr/bin/env bash

#------------------------------------------------------------------------------
# Project Name      - i3Config/source/.i3a/source_raise
# Started On        - Sun 24 Sep 00:30:17 BST 2017
# Last Change       - Wed 19 Jan 13:16:55 GMT 2022
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------

TargetDev='<alsa_input.usb-Burr-Brown_from_TI_USB_Audio_CODEC-00.analog-mono>'

while read; do
	if [[ $TargetFound == True && $REPLY =~ ^[[:space:]]+volume: ]]; then
		for Field in $REPLY; {
			(( ++FieldNr == 3 )) || continue

			# If it's less than 130%.
			if (( Field < 85113 )); then
				pactl set-source-volume '@DEFAULT_SOURCE@' +500
			fi
		}
	elif [[ $REPLY == *$TargetDev* ]]; then
		TargetFound='True'
	fi
done <<< "$(pacmd list-sources)"
