#!/usr/bin/env bash

#------------------------------------------------------------------------------
# Project Name      - i3Config/source/.i3a/source_raise
# Started On        - Sun 24 Sep 00:30:17 BST 2017
# Last Change       - Mon 17 Jan 20:22:10 GMT 2022
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------

while read; do
	if [[ $FoundTarget == True && $REPLY =~ ^\	volume:.* ]]; then
		read -a Line <<< "$REPLY"
		if (( ${Line[4]%\%} < 127 )); then
			pactl set-source-volume '@DEFAULT_SOURCE@' +500
		else
			exit 1
		fi
	elif [[ $REPLY == *'<alsa_input.usb-Burr-Brown_from_TI_USB_Audio_CODEC-00.analog-mono>'* ]]; then
		FoundTarget='True'
	fi
done <<< "$(pacmd list-sources)"
