#!/usr/bin/env bash
#cito M:600 O:1000 G:1000 T:$HOME/.i3a/term_font_size
#------------------------------------------------------------------------------
# Project Name      - i3Config/source/.i3a/term_font_size
# Started On        - Mon 30 Oct 15:14:16 GMT 2017
# Last Change       - Sun  1 Mar 22:07:44 GMT 2020
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------

set -e
. /usr/lib/tflbp-sh/Err
. /usr/lib/tflbp-sh/ChkDep
set +e

CurVer='2020-03-01'
Progrm=${0##*/}

Usage(){
	while read; do
		printf '%s\n' "$REPLY"
	done <<-EOF
		            ${Progrm^^} ($CurVer)
		            Written by terminalforlife <terminalforlife@yahoo.com>

		            Shortcut to raise or lower the xfce4-terminal font size.

		SYNTAX:     $Progrm [OPTS]

		OPTS:       --help|-h|-?            - Display this help information.
		            --version|-v            - Output version datestamp.
		            --lower|-l N            - Lower font size by N.
		            --quiet|-q              - Quieter operation, with errors.
		            --raise|-r N            - Raise font size by N.
		            --set|-s N              - Set font size to N.

		NOTE:       Due to the nature of the way in which this terminal
		            checks for and processes the changes to its configuration
		            file, this approach is sluggish to respond, but still
		            works nicely, for those running older versions.

		FILE:       ~/.config/xfce4/terminal/terminalrc
	EOF
}

CheckVal(){ [[ $1 =~ ^[0-9]+$ ]] || Err 1 'Invalid expression.'; }

while [ "$1" ]; do
	case $1 in
		--help|-h|-\?)
			Usage; exit 0 ;;
		--version|-v)
			printf '%s\n' "$CurVer"; exit 0 ;;
		--raise|-r)
			CheckVal "$2"
			declare -i Raise=$2

			shift ;;
		--lower|-l)
			CheckVal "$2"
			declare -i Lower=$2

			shift ;;
		--set|-s)
			CheckVal "$2"
			declare -i SetTo=$2

			shift ;;
		*)
			Err 1 'Incorrect argument(s) specified' ;;
	esac
	shift
done

ChkDep sed

Config="$HOME/.config/xfce4/terminal/terminalrc"

[ -f "$Config" ] || Err 1 'The configuration file is missing.'

while IFS='=' read Key Value; do
	case $Key in
		FontName)
			Now=${Value##* }
			break ;;
	esac
done < "$Config"

if [ -n "$Raise" ]; then
	sed -i "/^FontName=/s/${Now}$/$((Now+Raise))/" "$Config"
elif [ -n "$Lower" ]; then
	sed -i "/^FontName=/s/${Now}$/$((Now-Lower))/" "$Config"
elif [ -n "$SetTo" ]; then
	sed -i "/^FontName=/s/${Now}$/$SetTo/" "$Config"
fi
