#!/usr/bin/env bash

#------------------------------------------------------------------------------
# Project Name      - i3Config/source/.i3a/term_font_size
# Started On        - Mon 30 Oct 15:14:16 GMT 2017
# Last Change       - Sat  1 Feb 20:43:38 GMT 2020
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------

set -e
. /usr/lib/tflbp-sh/Err
. /usr/lib/tflbp-sh/ChkDep
set +e

CurVer='2020-02-01'
Progrm=${0##*/}

Usage(){
	while read -r CurLine; do
		printf '%b\n' "$CurLine"
	done <<-EOF
		\r            ${Progrm^^} ($CurVer)
		\r            Written by terminalforlife <terminalforlife@yahoo.com>

		\r            Shortcut to raise or lower the xfce4-terminal font size.

		\rSYNTAX:     $Progrm [OPTS]

		\rOPTS:       --help|-h|-?            - Display this help information.
		\r            --version|-v            - Output the version datestamp.
		\r            --quiet|-q              - Quieter operation, with errors.
		\r            --lower|-l N            - Lower font size by N.
		\r            --raise|-r N            - Raise font size by N.
		\r            --set|-s N              - Set font size to N.

		\rNOTE:       Due to the nature of the way in which this terminal
		\r            checks for and processes the changes to its configuration
		\r            file, this approach is sluggish to respond, but still
		\r            works nicely, for those running older versions.

		\rFILE:       ~/.config/xfce4/terminal/terminalrc
	EOF
}

CheckVal(){ [[ $1 =~ ^[0-9]+$ ]] || Err 1 'Invalid expression.'; }

while [ "$1" ]; do
	case $1 in
		--help|-h|-\?)
			Usage; exit 0 ;;
		--version|-v)
			printf '%s\n' "$CurVer"; exit 0 ;;
		--raise|-r)
			shift; CheckVal "$1"; declare -i Raise=$1 ;;
		--lower|-l)
			shift; CheckVal "$1"; declare -i Lower=$1 ;;
		--set|-s)
			shift; CheckVal "$1"; declare -i SetTo=$1 ;;
		*)
			Err 1 'Incorrect argument(s) specified' ;;
	esac
	shift
done

ChkDep sed

Config="$HOME/.config/xfce4/terminal/terminalrc"

[ -f "$Config" ] || Err 1 'The configuration file is missing.'

while IFS='=' read -a X; do
	[ "${X[0]}" == FontName ] && printf -v Now "%d" "${X[1]//[!0-9]/}"
done < "$Config"

if [ -n "$Raise" ]; then
	sed -i "/^FontName=/s/${Now}$/$((Now+Raise))/" "$Config"
elif [ -n "$Lower" ]; then
	sed -i "/^FontName=/s/${Now}$/$((Now-Lower))/" "$Config"
elif [ -n "$SetTo" ]; then
	sed -i "/^FontName=/s/${Now}$/$SetTo/" "$Config"
fi
