#!/bin/sh

#------------------------------------------------------------------------------
# Project Name      - i3Config/source/.i3a/terminal
# Started On        - Sat  1 Feb 15:11:16 GMT 2020
# Last Change       - Mon 18 Jan 23:39:23 GMT 2021
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------

case `hostname` in
	Z11)
		#"$HOME"/AppImages/Cool-Retro-Term-1.1.1-x86_64.AppImage ;;
		#terminator ;;
		xfce4-terminal ;;
	Sam)
		xfce4-terminal ;;
esac
