#!/usr/bin/env bash

#------------------------------------------------------------------------------
# Project Name      - i3Config/source/.i3a/term_font_size
# Started On        - Mon 30 Oct 15:14:16 GMT 2017
# Last Change       - Wed 11 Nov 16:31:51 GMT 2020
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------

CurVer='2020-11-11'
Progrm=${0##*/}

Usage(){
	while read; do
		printf '%s\n' "$REPLY"
	done <<-EOF
		Usage: $Progrm [OPTS]

		  -h, --help               - Displays this help information.
		  -v, --version            - Output only the version datestamp.
		  -l, --lower [N]          - Lower font size by N.
		  -q, --quiet              - Quieter operation, with errors.
		  -r, --raise [N]          - Raise font size by N.
		  -s, --set [N]            - Set font size to N.

		NOTE:    Due to the nature of the way in which this terminal checks for
		         and processes the changes to its configuration file, this
		         approach is sluggish to respond, but still works nicely, for
		         those running older versions.
	EOF
}

Err(){
	printf 'ERROR: %s\n' "$2" 1>&2
	[ $1 -eq 1 ] && exit 1
}

CheckVal(){ [[ $1 =~ ^[0-9]+$ ]] || Err 1 'Invalid expression.'; }

while [ "$1" ]; do
	case $1 in
		--help|-h|-\?)
			Usage; exit 0 ;;
		--version|-v)
			printf '%s\n' "$CurVer"; exit 0 ;;
		--raise|-r)
			CheckVal "$2"
			declare -i Raise=$2

			shift ;;
		--lower|-l)
			CheckVal "$2"
			declare -i Lower=$2

			shift ;;
		--set|-s)
			CheckVal "$2"
			declare -i SetTo=$2

			shift ;;
		*)
			Err 1 'Incorrect argument(s) specified' ;;
	esac
	shift
done

ChkDep sed

Config="$HOME/.config/xfce4/terminal/terminalrc"

[ -f "$Config" ] || Err 1 'The configuration file is missing.'

while IFS='=' read Key Value; do
	case $Key in
		FontName)
			Now=${Value##* }
			break ;;
	esac
done < "$Config"

if [ -n "$Raise" ]; then
	sed -i "/^FontName=/s/${Now}$/$((Now+Raise))/" "$Config"
elif [ -n "$Lower" ]; then
	sed -i "/^FontName=/s/${Now}$/$((Now-Lower))/" "$Config"
elif [ -n "$SetTo" ]; then
	sed -i "/^FontName=/s/${Now}$/$SetTo/" "$Config"
fi
