#!/bin/sh

#------------------------------------------------------------------------------
# Project Name      - i3Config/source/.i3a/terminal
# Started On        - Sat  1 Feb 15:11:16 GMT 2020
# Last Change       - Fri  7 Feb 15:37:46 GMT 2020
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------

case `hostname` in
	Z11) terminology 1> /dev/null 2>&1 || xfce4-terminal 1> /dev/null 2>&1 ;;
	Sam) xfce4-terminal 1> /dev/null 2>&1 || terminology 1> /dev/null 2>&1 ;;
esac
