#!/usr/bin/env bash

#------------------------------------------------------------------------------
# Project Name      - i3Config/source/.i3a/toggle_loopback
# Started On        - Mon 13 Dec 22:38:45 GMT 2021
# Last Change       - Fri 18 Mar 01:33:45 GMT 2022
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# Toggle the use of the input audio loopback device with PulseAudio.
#------------------------------------------------------------------------------

while read _ Module _; do
	if [[ $Module = module-loopback ]]; then
		Status='Enabled'

		break
	fi
done <<< "$(pactl list short modules)"

if [[ $Status == Enabled ]]; then
	pactl unload-module module-loopback
else
	pactl load-module module-loopback
fi
