#!/bin/sh

#------------------------------------------------------------------------------
# Project Name      - i3Config/source/.i3a/track_notify
# Started On        - Sat 23 Sep 14:47:51 BST 2017
# Last Change       - Tue  3 Mar 16:24:10 GMT 2020
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------

Buffer=`mocp --format='%file'`
notify-send "${Buffer##*/}"
