#!/bin/sh

#------------------------------------------------------------------------------
# Project Name      - i3Config/source/.i3a/use_dmenu
# Started On        - Sat 23 Sep 14:47:51 BST 2017
# Last Change       - Tue  3 Mar 16:12:18 GMT 2020
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# You may need to install the Debian/Ubuntu 'suckless-tools' package.
#
# #BBGGYY (B = blue, G = green, Y = yellow)
# #ffffff = white  |  #000000 = black
#
# See man 1 dmenu for more information.
#
# Set the ALT variable to one of the "ALT" == "VAR" variables, where VAR is the
# name for the configuration I found online, or leave it blank to use my own.
#------------------------------------------------------------------------------

Launcher(){
	dmenu_run -b -fn "$1":style=Bold:size=12 -nb \#000000\
		-nf \#ffffff -sb \#550000 -sf \#ffffff

	exit 0
}

fc-list : family | while read CurLine; do
	case $CurLine in
		        'FreeMono') Launcher 'FreeMono' ;;
		     'Oxygen Mono') Launcher 'Oxygen Mono' ;;
		     'Ubuntu Mono') Launcher 'Ubuntu Mono' ;;
		'Ricty Diminished') Launcher 'Ricty Diminished' ;;
	esac
done
