#!/usr/bin/env perl

#----------------------------------------------------------------------------------
# Project Name      - i3Config/dev_setup
# Started On        - Fri 10 May 23:28:31 BST 2019
# Last Change       - Fri  8 Nov 00:24:12 GMT 2019
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------
# This Perl script will set up my development environment, effectively using the
# terminal layout I usually always want. And yes, it addresses the split problem.
#
# Eventually, I'll probably come up with something like this which isn't just for
# me, but can be used by anyone; perhaps my own take on a layout save/restore.
#
# That said, as long as you follow the syntax you already see, you could probably
# set things up the way you want to, easily enough, using TFL::i3Do().
#----------------------------------------------------------------------------------

use strict;
use warnings;
use autodie;
use File::Basename 'basename';
use TFL; # <-- libtfl-perl (>= 2019-05-07)

my $_VERSION_ = "2019-11-08";

my %EXECS = (
	'TERMINAL' => 'xfce4-terminal',
	'BROWSER' => 'firefox',
	'EMAIL' => 'thunderbird'
);

TFL::DepChk('/usr/bin/' . $EXECS{$_}) foreach keys(%EXECS);

TFL::i3Do(400000, 'workspace 1'); # <-- In-case the user doesn't start here.

my $GH_REPOS = $ENV{HOME} . '/GitHub/terminalforlife/Personal';
my $WD = "--working-directory='$GH_REPOS'";

# New, 1-terminal development layout.
TFL::i3Do(400000, "exec --no-startup-id $EXECS{TERMINAL} $WD");

# Previous, 3-terminal development layout.
#TFL::i3Do(400000, "exec --no-startup-id $EXECS{TERMINAL} $WD") foreach (1..2);
#TFL::i3Do(400000, 'split v'); # <-- YMMV, regarding the integer.
#TFL::i3Do(400000, "exec --no-startup-id $EXECS{TERMINAL} $WD");
#TFL::i3Do(400000, 'focus left');

# Assumes appropriate for_windows have been set.
TFL::i3Do(400000, "exec --no-startup-id $EXECS{CHAT}"); # <-- WS 3.
TFL::i3Do(400000, "exec --no-startup-id $EXECS{BROWSER}"); # <-- WS 4.
TFL::i3Do(400000, "exec --no-startup-id $EXECS{EMAIL}"); # <-- WS 7.

TFL::i3Do(400000, 'workspace 10');

if(basename($EXECS{TERMINAL}) eq 'xfce4-terminal'){
	TFL::DepChk('/usr/bin/mplay'); TFL::DepChk('/usr/bin/mocp');

	my $FILE = $ENV{HOME} . '/.i3a/partmount';
	TFL::i3Do(400000, "bash $FILE -L 'Media 3'") if -f $FILE and -r $FILE;
	TFL::i3Do(400000, "exec --no-startup-id $EXECS{TERMINAL} -x 'mplay'")
}else{
	TFL::i3Do(400000, "exec --no-startup-id $EXECS{TERMINAL}")
}

TFL::i3Do(400000, 'workspace 1');
