#!/bin/sh

#----------------------------------------------------------------------------------
# Project Name      - $HOME/.i3a/dmesg_overflow
# Started On        - Sun  5 Nov 12:04:09 GMT 2017
# Last Change       - Wed 27 Nov 00:33:34 GMT 2019
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------
# Because of the very excessive amount of permission errors muddying up, -
# $HOME/.xsession_errors, this addon will erase the file at login, if it detects
# the errors. This should be quick and painless, with only a minor chance to remove
# important logged information. A quick workaround to a frustrating issue that is
# better than allowing dmesg to be a free-for-all!
#
# If this issue is something you've never experienced, you needn't use this script.
#----------------------------------------------------------------------------------

ProcFile='/proc/sys/kernel/dmesg_restrict'

if [ -f "$ProcFile" ]; then
	read Result < "$ProcFile"

	if [ $Result -eq 1 ]; then
		ErrMSG='dmesg: read kernel buffer failed: Operation not permitted'
		LogFile="$HOME/.xsession-errors"

		if [ -f "$LogFile" ] && [ -r "$LogFile" ]; then
			while read CurLine; do
				if [ "$CurLine" = "$ErrMSG" ] && [ -w "$LogFile" ]; then
					rm -f "$LogFile"
					break
				fi
			done < "$LogFile"
		fi
	fi
fi
