#!/usr/bin/env bash

#----------------------------------------------------------------------------------
# Project Name      - $HOME/.i3a/drop_terminal
# Started On        - Sat 23 Sep 14:47:51 BST 2017
# Last Change       - Mon 13 May 01:11:03 BST 2019
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------
# Allows the user to launch a drop-down terminal, such as guake, tilda, or
# xfce4-terminal's own built-in drop-down feature.
#------------------------------------------------------------------------DMENU HERE

TERMINAL_ARGS="--fullscreen --drop-down"
TERMINAL_PATH="/usr/bin/xfce4-terminal"
MASTER="alsa_input.usb-Burr-Brown_from_TI_USB_Audio_CODEC-00.analog-stereo"
SOUND05="/usr/share/sounds/freedesktop/stereo/dialog-information.oga"
/usr/bin/paplay --volume 40000 "$SOUND05" & disown
$TERMINAL_PATH $TERMINAL_ARGS
