#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - $HOME/.i3a/dtrecord
# Started On        - Sat 23 Sep 14:47:51 BST 2017
# Last Change       - Sat 14 Oct 12:03:40 BST 2017
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

#TODO - Fix. Sound plays, but doesn't seem to start recording.

[ $UID -eq 0 ] && exit 1

[ -x /bin/mkdir ] && {
	FILENAME="$HOME/Desktop/DT_`printf '%(%F_%X)T'`.mkv"
	[ -d "${FILENAME%\/*}" ] || /bin/mkdir -p "${FILENAME%\/*}"
	SOUNDFILE="/usr/share/sounds/Oxygen-K3B-Finish-Success.ogg"

	{ [ -f "$SOUNDFILE" ] && [ -r "$SOUNDFILE" ]; } && {
		/usr/bin/paplay --volume 40000 "$SOUNDFILE"
	}
	
	if [ "$DT_REC_MODE" == "false" ]
	then
		[ -x /usr/bin/ffmpeg ] && {
			/usr/bin/ffmpeg -f x11grab -video_size 1920x1080\
				-framerate 60 -i :0.0 "$FILENAME"
	
			export DT_REC_PID=`/usr/bin/lsof -t "$FILENAME"`
			export DT_REC_MODE="true"
		}
	else
		kill -HUP $DT_REC_PID
		export DT_REC_MODE="false"
	fi
}
