#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - $HOME/.i3a/feh_slides
# Started On        - Sun  5 Nov 12:04:09 GMT 2017
# Last Change       - Wed 14 Mar 12:17:54 GMT 2018
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

while [ -n "$1" ]; do
	case "$1" in
		-i)
			shift
			INTERVAL="$1" ;;
		-d)
			shift
			DIR="$1" ;;
		*)
			exit 1 ;;
	esac

	shift
done

[ -d "$DIR" ] || exit 3

while :; do
	for FILE in "${DIR%\/}"/*; {
		if [ -f "$FILE" ]; then
			/usr/bin/feh --no-fehbg --bg-center "$FILE"
			/bin/sleep ${INTERVAL:-5s}
		fi
	}
done

# vim: noexpandtab colorcolumn=84 tabstop=8 noswapfile nobackup
