#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - i3config/.i3a/hush_the_mic
# Started On        - Sun 11 Feb 12:38:53 GMT 2018
# Last Change       - Sun 11 Feb 13:02:00 GMT 2018
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------
# Gradually decrease the microphone volume. This small script will make use of
# PulseAudio, via /usr/bin/pactl. Steals code from: i3config/.i3a/source_lower
#----------------------------------------------------------------------------------

XERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; exit 1; }
ERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; }

declare -i DEPCOUNT=0
for DEP in /bin/sleep /usr/bin/{pactl,pacmd}; {
	[ -x "$DEP" ] || {
		ERR "$LINENO" "Dependency '$DEP' not met."
		DEPCOUNT+=1
	}
}

[ $DEPCOUNT -eq 0 ] || exit 1

MASTER="alsa_input.usb-Burr-Brown_from_TI_USB_Audio_CODEC-00.analog-stereo"

while :; do
	while read -a X; do
		if [ "${X[0]}" == volume: ]; then
			if ! [ "$FIRST" == "true" ]; then
				FIRST="true"
				continue
			fi
	
			if [ ${X[2]} -eq 0 ]; then
				exit 0
			fi
		fi
	
	done <<< "$(/usr/bin/pacmd list-sources)"

	/usr/bin/pactl set-source-volume "$MASTER" -150
	/bin/sleep 0.2
done
