#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - $HOME/.i3a/i3bar_trans
# Started On        - Sat 17 Feb 01:34:23 GMT 2018
# Last Change       - Wed 11 Apr 10:08:21 BST 2018
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------
# Make the i3-wm bars transparent. Sadly also affects text, but it does have a nice
# effect and makes the bars, text included, more subtle. Looks very charming. This
# should work on any number of i3bar instances currently loaded.
#
# SYNTAX:     i3bar_trans VALUE
#
# Where VALUE is the transparency number, between 0 and 1. Floating point is
# allowed. 0 is invisible, and 1 is completely opaque.
#----------------------------------------------------------------------------------

while read -a X; do
	if [ "${X[1]/\"}${X[2]}${X[3]}" == "i3barforoutput" ]; then
		if [ -x /usr/bin/transset ]; then
			/usr/bin/transset $1 -i "${X[0]}"
		elif [ -x /usr/bin/transset-df ]; then
			/usr/bin/transset-df $1 -i "${X[0]}"
		fi
	fi
done <<< "$(/usr/bin/xwininfo -root -all)"

# vim: ft=sh noexpandtab colorcolumn=84 tabstop=8 noswapfile nobackup
