#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - $HOME/.i3a/initialize
# Started On        - Sat 23 Sep 14:47:51 BST 2017
# Last Change       - Fri 12 Apr 10:32:24 BST 2019
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

BACKGROUND="$HOME/Pictures/Wallpapers/trees_asphalt_path_gray_55415_1920x1080.jpg"
FEH_SLIDES="$HOME/Pictures/Wallpapers"
BELLSND="/usr/share/sounds/freedesktop/stereo/message.oga"
ALERTSND="/usr/share/sounds/freedesktop/stereo/window-attention.oga"
SOUND04="/usr/share/sounds/freedesktop/stereo/service-login.oga"
DUNSTRC="$HOME/.config/dunst/dunstrc"
COMPCONF="$HOME/.config/compton.conf"
REDSHIFTER="$HOME/.config/redshifter.tmp"

# Redshift sets the gamma to the previous value, per REDSHIFTER file. You will
# probably want to install redshifter for this: sudo insit redshifter
/usr/bin/redshift -O `< "$REDSHIFTER"`K & disown

# Load compton (lightweight compositing manager) and its config file. My config
# file can be found in the miscellaneous repository. Or use your own. If you don't
# want to use a config file, change the following compton command as applicable.
if [ -x /usr/bin/compton ]; then
	if [ -f "$COMPCONF" -a -r "$COMPCONF" ]; then
		/usr/bin/compton --config "$COMPCONF" -b & disown
	fi
elif [ -x /usr/bin/xcompmgr ]; then
	/usr/bin/xcompmgr -cCfFn
fi

# Load up dunst, a lightweight and feature-rich notification daemon.
/usr/bin/dunst -config "$DUNSTRC" & disown

#TODO - Address multitude of permission errors. (due to dmesg restrict)
# Load up a small script which uses your notification daemon and notify-send to
# display notifications upon certain system changes reported by the kernel. This
# can be found in the miscellaneous repository.
#/usr/bin/syswatch & disown

# Be sure pulseaudio is enabled. Don't try to start unless inactive, just in-case.
/usr/bin/pulseaudio --check || /usr/bin/pulseaudio --start & disown

# Enable the bell sound.
/usr/bin/pacmd load-module module-x11-bell

# Also load up an alert sound to be used by shell programs.
/usr/bin/pactl upload-sample $ALERTSND x11-alert & disown

# Set bar transparency.
/bin/bash $HOME/.i3a/i3bar_trans 0.5 & disown


# Set the background image, using either feh, nitrogen, and/or feh-slides.
if [ -x /usr/bin/feh-slides ]; then
	/usr/bin/feh-slides -i 7s "$FEH_SLIDES" & disown
else
	if [ -x /usr/bin/feh ]; then
		/usr/bin/feh --no-fehbg --bg-center $BACKGROUND & disown
	elif [ -x /usr/bin/nitrogen ]; then
		/usr/bin/nitrogen "$BACKGROUND" & disown
	fi
fi

# Enable the use of Ctrl + Alt + Backspace to kill X. No point in setting this if
# the below kernel parameter is set to 1, so test for that too.
if [ `< /proc/sys/kernel/ctrl-alt-del` -eq 0 ] && [ -x /usr/bin/setxkbmap ]; then
	/usr/bin/setxkbmap -option terminate:ctrl_alt_bksp & disown
fi

/usr/bin/xsetroot -solid "#000000" & disown

# Set bell volume to 70%, disable DPMS (power-saving for your monitor), and set the
# keyboard repeat delay and rate.
/usr/bin/xset b 50 -dpms r rate 170 70 & disown

# Remap F1 to Esc, and disable Caps Lock.
/usr/bin/xmodmap -e "keysym F1 = Escape" -e "clear lock" & disown

# Load keynav to get mouse controls with a keyboard.
/usr/bin/keynav & disown

# Play a little sound upon login. Uses a path at the start of this script.
/usr/bin/paplay --volume 40000 "$SOUND04" & disown

# Check for kernel version changes; see kernelchk repository.
/usr/bin/kernelchk -N -b & disown

# Launches mocp in the background, ready for music.
/usr/bin/mocp -S & disown
