#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - $HOME/.i3a/key_autorepeat
# Started On        - Wed  1 Nov 00:50:35 GMT 2017
# Last Change       - Wed 14 Mar 14:32:29 GMT 2018
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------
# Toggle the key autorepeat feature on and off. Uses simple flag file.
#----------------------------------------------------------------------------------

MASTER="alsa_input.usb-Burr-Brown_from_TI_USB_Audio_CODEC-00.analog-stereo"
SOUND05="$HOME/.config/i3/Sounds/SND03.wav"
TOGFILE="$HOME/.config/key_auto"
[ -d "${TOGFILE/%\/*}" ] || /bin/mkdir "${TOGFILE/%\/*}"
/usr/bin/paplay --volume 40000 "$SOUND05" & disown
if [ -f "$TOGFILE" -a -r "$TOGFILE" ]; then
	/bin/rm "$TOGFILE"
	/usr/bin/xset r off
else
	> "$TOGFILE"
	/usr/bin/xset r on
fi

# vim: noexpandtab colorcolumn=84 tabstop=8 noswapfile nobackup
