#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - $HOME/.i3a/key_autorepeat
# Started On        - Wed  1 Nov 00:50:35 GMT 2017
# Last Change       - Wed  1 Nov 17:32:02 GMT 2017
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

# Work in progress. Toggle the key autorepeat feature on and off.

#----------------------------------------------------------------------------------

[ $UID -eq 0 ] && exit 1

MASTER="alsa_input.usb-Burr-Brown_from_TI_USB_Audio_CODEC-00.analog-stereo"
SOUND05="$HOME/.config/i3/Sounds/SND03.wav"

[ -f "$SOUND05" ] || exit 1

[ -x /usr/bin/pactl ] && {
	/usr/bin/paplay --volume 40000 "$SOUND05" & disown

	B=$(
		
	)
}
