#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - $HOME/.i3a/lockscreen
# Started On        - Thu  4 Apr 12:38:37 BST 2019
# Last Change       - Wed 17 Apr 00:04:50 BST 2019
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

#TODO - If the lock key is held, multiple instances of this script are executed.

set -o errexit

FILE="$(/bin/mktemp -u --suffix='_lock.png')"
SOUND03="/usr/share/sounds/freedesktop/stereo/network-connectivity-lost.oga"
SOUND04="/usr/share/sounds/freedesktop/stereo/network-connectivity-established.oga"

trap "/bin/rm -f $FILE" EXIT

TEMPSOUND="$HOME/Documents/Sound Files/Sound Effects/button-24.wav"

/usr/bin/scrot -z "$FILE"
/usr/bin/convert "$FILE" -gaussian-blur 8x8 "$FILE"
/usr/bin/paplay --volume 40000 "$SOUND03" &
/usr/bin/i3lock -u -n -i "$FILE"
/usr/bin/paplay --volume 40000 "$SOUND04" &
