#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - $HOME/.i3a/partmount
# Started On        - Mon 15 Jan 20:17:34 GMT 2018
# Last Change       - Wed 14 Mar 12:20:29 GMT 2018
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------
# A work in progress. Toggle-mount partitions with a simple keyboard shortcut.
#
# SYNTAX:    partmount [OPTS]
#
# ARGS:      --uuid|-U UUID       - Where UUID is one of the filesystem to mount.
#            --label|-L LABEL     - Where LABEL is one of the filesystem to mount.
#            --name|-N NAME       - Where NAME is one of the filesystem to mount.
#
# NOTE:      NAME is the block device name, for example: /dev/sda1
#----------------------------------------------------------------------------------

while [ "$1" ]; do
	case "$1" in
		--uuid|-U)
			shift; UUID="$1"
			[ -z "$UUID" ] && exit 1 ;;
		--label|-L)
			shift; LABEL="${1// /\\x20}"
			[ -z "$LABEL" ] && exit 1 ;;
		--name|-N)
			shift; NAME="$1"
			[ -z "$NAME" ] && exit 1 ;;
	esac
	shift
done

if [ "$UUID" ]; then
	if [ -e /dev/disk/by-uuid/"$UUID" ]; then
		if ! /usr/bin/udisksctl mount -b /dev/disk/by-uuid/"$UUID"; then
			if /usr/bin/udisksctl unmount -b /dev/disk/by-uuid/"$UUID"; then
				/usr/bin/notify-send --urgency=critical\
					"PARTMOUNT: Unable to unmount file system."
			fi
		fi
	else
		/usr/bin/notify-send --urgency=critical\
			"PARTMOUNT: Chosen UUID is invalid or unavailable."
	fi
elif [ "$LABEL" ]; then
	if [ -e /dev/disk/by-label/"$LABEL" ]; then
		if ! /usr/bin/udisksctl mount -b /dev/disk/by-label/"$LABEL"; then
			if ! /usr/bin/udisksctl unmount -b /dev/disk/by-label/"$LABEL"; then
				/usr/bin/notify-send --urgency=critical\
					"PARTMOUNT: Unable to unmount file system."
			fi
		fi
	else
		/usr/bin/notify-send --urgency=critical\
			"PARTMOUNT: Chosen LABEL is invalid or unavailable."
	fi
elif [ "$NAME" ]; then
	if [ -e /dev/disk/by-name/"$NAME" ]; then
		if ! /usr/bin/udisksctl mount -b "$NAME"; then
			if ! /usr/bin/udisksctl unmount -b "$NAME"; then
				/usr/bin/notify-send --urgency=critical\
					"PARTMOUNT: Unable to unmount file system."
			fi
		fi
	else
		/usr/bin/notify-send --urgency=critical\
			"PARTMOUNT: Chosen NAME is invalid or unavailable."
	fi
fi

# vim: noexpandtab colorcolumn=84 tabstop=8 noswapfile nobackup
