#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - $HOME/.i3a/scrot_sel_take
# Started On        - Sat 23 Sep 14:47:51 BST 2017
# Last Change       - Fri 20 Oct 14:18:37 BST 2017
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

[ $UID -eq 0 ] && exit 1

{ [ -x /usr/bin/scrot ] && [ -x /usr/bin/paplay ]; } && {
	FILENAME="$HOME/Desktop/Selectshot_`printf '%(%F_%X)T'`.png"
	SOUND03="/usr/share/sounds/freedesktop/stereo/screen-capture.oga"
	TEMPSOUND="$HOME/Documents/Sound Files/Sound Effects/button-24.wav"

	for FILE in "$SOUND03" "$TEMPSOUND"; {
		[ -f "$FILE" ] || exit 1
	}

	# This just lets you know you pressed the button and that it's waiting for
	# you to select with the mouse the area of the screen to capture.
	/usr/bin/paplay --volume 30000 "$TEMPSOUND"

	# Image will be highest quality in PNG format, saved to: $HOME/Desktop
	/usr/bin/scrot -s -q 100 "$FILENAME"  && {
		/usr/bin/paplay --volume 40000 "$SOUND03"
	}
}
