#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - $HOME/.i3a/scrot_sel_take
# Started On        - Sat 23 Sep 14:47:51 BST 2017
# Last Change       - Wed 14 Mar 12:21:58 GMT 2018
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------
# Take a screenshot of the user-selected square region, using scrot.
#----------------------------------------------------------------------------------

umask 0077

if [ "$1" == "--lite" ]; then
	printf -v FILENAME "$HOME/Desktop/.lmscrot.jpg"
else
	printf -v FILENAME "$HOME/Desktop/Selectshot_%(%F_%X)T.jpg"
fi

SOUND03="/usr/share/sounds/freedesktop/stereo/screen-capture.oga"
TEMPSOUND="$HOME/Documents/Sound Files/Sound Effects/button-24.wav"
/usr/bin/paplay --volume 30000 "$TEMPSOUND"
if /usr/bin/scrot -zsq 75 -d 1 "$FILENAME"; then
	/usr/bin/paplay --volume 40000 "$SOUND03"
fi

# vim: noexpandtab colorcolumn=84 tabstop=8 noswapfile nobackup
