#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - $HOME/.i3a/sink_lower
# Started On        - Sun 24 Sep 00:30:17 BST 2017
# Last Change       - Thu 22 Feb 18:00:29 GMT 2018
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

[ $UID -eq 0 ] && exit 1

MASTER="alsa_output.usb-Burr-Brown_from_TI_USB_Audio_CODEC-00.analog-stereo"

if [ -x /usr/bin/pacmd ]; then
	while read -a X; do
		if [[ "${X[0]}" =~ volume: ]]; then
			printf -v VOL "%d" "${X[4]%\%}"
			[ $VOL -eq 0 ] && exit 0 || break
		fi
	done <<< "$(/usr/bin/pacmd list-sinks)"
fi

if [ -x /usr/bin/pactl ]; then
	/usr/bin/pactl play-sample x11-volume-change & disown
	/usr/bin/pactl set-sink-volume "$MASTER" -500
fi

# vim: noexpandtab colorcolumn=84 tabstop=8 noswapfile nobackup
