#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - $HOME/.i3a/sink_lower
# Started On        - Sun 24 Sep 00:30:17 BST 2017
# Last Change       - Thu 11 Apr 11:27:35 BST 2019
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

if [ -x /usr/bin/pacmd ]; then
	while IFS=":" read -a X; do
		[ "${X[0]}" == "Default sink name" ] && MASTER="${X[1]## }"
	done <<< "$(/usr/bin/pacmd info)"

	while read -a X; do
		if [[ "${X[0]}" =~ volume: ]]; then
			printf -v VOL "%d" "${X[4]%\%}"
			[ $VOL -le 0 ] && exit 0 || break
		fi
	done <<< "$(/usr/bin/pacmd list-sinks)"

	if [ -x /usr/bin/pactl ]; then
		/usr/bin/pactl play-sample x11-volume-change & disown
		/usr/bin/pactl set-sink-volume "$MASTER" -500
	fi

	if [ -x /usr/bin/pkill ]; then
		# Use 'signal=1' and 'interval=once' in the i3blocks configuration
		# file, in order to have this update only when needed.
		/usr/bin/pkill -RTMIN+1 i3blocks
	fi
fi

# vim: ft=sh noexpandtab colorcolumn=84 tabstop=8 noswapfile nobackup
