#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - $HOME/.i3a/master_mute
# Started On        - Sun 24 Sep 00:30:17 BST 2017
# Last Change       - Wed  1 Nov 21:26:28 GMT 2017
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

[ $UID -eq 0 ] && exit 1

MASTER="alsa_output.usb-Burr-Brown_from_TI_USB_Audio_CODEC-00.analog-stereo"
[ /usr/bin/pactl ] && /usr/bin/pactl set-sink-mute "$MASTER" toggle

# vim: noexpandtab colorcolumn=84 tabstop=8 noswapfile nobackup
