#!/usr/bin/env bash

#----------------------------------------------------------------------------------
# Project Name      - $HOME/.i3a/sink_raise
# Started On        - Sun 24 Sep 00:30:17 BST 2017
# Last Change       - Mon 13 May 01:17:15 BST 2019
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------
# This script is more of a personal one than any of the others. I have two devices
# I switch between the mixer and the monitor's speakers. Headphones on the former.
#----------------------------------------------------------------------------------

DEV_1='alsa_output.usb-Burr-Brown_from_TI_USB_Audio_CODEC-00.analog-stereo'
DEV_2='alsa_card.pci-0000_01_00.1.hdmi-stereo-extra1'

if type -fP pacmd > /dev/null 2>&1; then
	while IFS=":" read -a X; do
		[ "${X[0]}" == "Default sink name" ] && MASTER="${X[1]## }"
	done <<< "$(pacmd info)"

	echo "$MASTER"

	if type -fP pactl > /dev/null 2>&1; then
		pactl play-sample x11-volume-change & disown

		if [ "$MASTER" == "$DEV_1" ]; then
			pactl set-card-profile "${DEV_2%.*}" output:hdmi-stereo-extra1
		else
			pactl set-card-profile "${DEV_2%.*}" off
		fi
	fi
fi

