#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - $HOME/.i3a/master_raise
# Started On        - Sun 24 Sep 00:30:17 BST 2017
# Last Change       - Wed  1 Nov 21:35:45 GMT 2017
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

[ $UID -eq 0 ] && exit 1

MASTER="alsa_output.usb-Burr-Brown_from_TI_USB_Audio_CODEC-00.analog-stereo"

[ -x /usr/bin/pacmd ] && {
	while read -ra X; do
		[[ "${X[*]}" == *volume\:\ front-left\:\ +([0-9])* ]] && {
			printf -v VOL "%d" "${X[2]}" # "$(( X[2] + 1500 ))"
			[ $VOL -ge 65550 ] && exit 0 || break
		}
	done <<< "$(/usr/bin/pacmd list-sinks)"
}

[ -x /usr/bin/pactl ] && {
	/usr/bin/pactl play-sample x11-volume-change & disown
	/usr/bin/pactl set-sink-volume "$MASTER" +500
}
