#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - $HOME/.i3a/master_mute
# Started On        - Sun 24 Sep 00:30:17 BST 2017
# Last Change       - Wed 14 Mar 12:24:41 GMT 2018
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

MASTER="alsa_output.usb-Burr-Brown_from_TI_USB_Audio_CODEC-00.analog-stereo"
/usr/bin/pactl set-sink-mute "$MASTER" toggle

# vim: noexpandtab colorcolumn=84 tabstop=8 noswapfile nobackup
