#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - $HOME/.i3a/source_raise
# Started On        - Sun 24 Sep 00:30:17 BST 2017
# Last Change       - Sat 14 Oct 12:16:28 BST 2017
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

[ $UID -eq 0 ] && exit 1

MASTER="alsa_input.usb-Burr-Brown_from_TI_USB_Audio_CODEC-00.analog-stereo"
SOUND05="$HOME/.config/i3/Sounds/SND03.wav"

[ -x /usr/bin/pactl ] && {
	/usr/bin/paplay --volume 40000  "$SOUND05"
	/usr/bin/pactl set-source-volume "$MASTER" +250
}
