#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - $HOME/.i3a/source_lower
# Started On        - Sun 24 Sep 00:30:17 BST 2017
# Last Change       - Sun 11 Feb 13:07:53 GMT 2018
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

[ $UID -eq 0 ] && exit 1

MASTER="alsa_input.usb-Burr-Brown_from_TI_USB_Audio_CODEC-00.analog-stereo"

if [ -x /usr/bin/pacmd ]; then
	while read -a X; do
		if [ "${X[0]}" == volume: ]; then
			if ! [ "$FIRST" == "true" ]; then
				FIRST="true"
				continue
			fi

			[ ${X[2]} -eq 0 ] && exit 0
		fi

	done <<< "$(/usr/bin/pacmd list-sources)"
fi

if [ -x /usr/bin/pactl ]; then
	/usr/bin/pactl play-sample x11-volume-change & disown
	/usr/bin/pactl set-source-volume "$MASTER" -500
fi
