#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - $HOME/.i3a/source_lower
# Started On        - Sun 24 Sep 00:30:17 BST 2017
# Last Change       - Mon 23 Oct 01:45:51 BST 2017
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

[ $UID -eq 0 ] && exit 1

SOUND05="$HOME/.config/i3/Sounds/SND03.wav"
[ -f "$SOUND05" ] || exit 1

[ -x /usr/bin/pactl ] && {
	/usr/bin/paplay --volume 40000 "$SOUND05"
	/usr/bin/pactl set-source-volume -250
}
