#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - $HOME/.i3a/source_raise
# Started On        - Sun 24 Sep 00:30:17 BST 2017
# Last Change       - Thu 11 Apr 11:29:39 BST 2019
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

if [ -x /usr/bin/pacmd ]; then
	while IFS=":" read -a X; do
		[ "${X[0]}" == "Default source name" ] && MASTER="${X[1]## }"
	done <<< "$(/usr/bin/pacmd info)"

	while read -a X; do
		if [ "${X[0]}" == volume: ]; then
			if ! [ "$FIRST" == "true" ]; then
				FIRST="true"
				continue
			fi

			[ ${X[2]} -ge 98000 ] && exit 0
		fi
	done <<< "$(/usr/bin/pacmd list-sources)"

	if [ -x /usr/bin/pactl ]; then
		/usr/bin/pactl play-sample x11-volume-change & disown
		/usr/bin/pactl set-source-volume "$MASTER" +500
	fi

	if [ -x /usr/bin/pkill ]; then
		# Use 'signal=1' and 'interval=once' in the i3blocks configuration
		# file, in order to have this update only when needed.
		/usr/bin/pkill -RTMIN+1 i3blocks
	fi
fi

# vim: ft=sh noexpandtab colorcolumn=84 tabstop=8 noswapfile nobackup
