#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - $HOME/.i3a/source_mute
# Started On        - Sun 24 Sep 00:30:17 BST 2017
# Last Change       - Wed 14 Mar 12:24:32 GMT 2018
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

MASTER="alsa_input.usb-Burr-Brown_from_TI_USB_Audio_CODEC-00.analog-stereo"
SOUND05="$HOME/.config/i3/Sounds/SND03.wav"
/usr/bin/paplay --volume 40000 "$SOUND05" & disown
/usr/bin/pactl set-source-mute "$MASTER" toggle

# vim: noexpandtab colorcolumn=84 tabstop=8 noswapfile nobackup
