#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - $HOME/.i3a/terminal
# Started On        - Sat 23 Sep 14:47:51 BST 2017
# Last Change       - Wed 14 Mar 12:27:56 GMT 2018
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------
# If your executable has spaces in the filename, or any other, non-standard
# characters, be sure to write it "like this", 'like this', or\ like\ this. Special
# characters include (but are not limited to), &, +, ?, and *.
#
# LIMIT is to set the maximum number of processes of your chosen terminal. This
# helps avoid overloading your system with excessive numbers of terminals by
# mistake, such as when you have a fast key autorepeat, a stuck key, or a troll.
# A notication will be sent to notify the user, if /usr/bin/notify-send is found.
#
# NOTE: Arguments for your chosen terminal should work just fine. You can also set
#       the LIMIT parameter to 0 if you wish to ignore the limiting functionality.
#----------------------------------------------------------------------------------

#TODO - The LIMIT doesn't work with xfce4-terminal,as it uses just the one process.

T='/usr/bin/xfce4-terminal'
LIMIT=0

#-------------------------------------------------------------------------MAIN CODE

if [ -x "$T" ]; then
	if ! [ $LIMIT -eq 0 ] && [ -x /bin/ps ]; then
		read -a X <<< `/bin/ps --no-headers -C "${T//*\/}" -o pid`

		if [ ${#X[@]} -ge $LIMIT ]; then
			if [ -x /usr/bin/notify-send ]; then
				MSG="The maximum ${T//*\/} processes was reached."
				/usr/bin/notify-send --urgency=normal "$MSG"
				exit 2
			else
				exit 2
			fi
		else
			$T & exit 0
		fi
	else
		$T & exit 0
	fi
else
	exit 1
fi

# vim: noexpandtab colorcolumn=84 tabstop=8 noswapfile nobackup
