#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - $HOME/.i3a/terminal
# Started On        - Sat 23 Sep 14:47:51 BST 2017
# Last Change       - Sat 14 Oct 12:16:44 BST 2017
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

[ $UID -eq 0 ] && exit 1

[ -x /usr/bin/xfce4-terminal ] && /usr/bin/xfce4-terminal
