#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - $HOME/.i3a/track_notify
# Started On        - Sat 23 Sep 14:47:51 BST 2017
# Last Change       - Mon 23 Oct 13:00:54 BST 2017
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

[ $UID -eq 0 ] && exit 1

{ [ -x /usr/bin/notify-send ] && [ -x /usr/bin/mocp ] && [ -x /bin/sed ]; } && {
	NOTIFICATION=$(
		/usr/bin/mocp --format="%file"\
			| /bin/sed 's/^.*\///; s/\.[A-Za-z0-9]\+$//'
			#TODO - Use pure shell method in place of sed.
	)
	
	/usr/bin/notify-send  "$NOTIFICATION"
}
