#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - $HOME/.i3a/track_notify
# Started On        - Sat 23 Sep 14:47:51 BST 2017
# Last Change       - Tue 24 Oct 14:44:08 BST 2017
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

[ $UID -eq 0 ] && exit 1

{ [ -x /usr/bin/notify-send ] && [ -x /usr/bin/mocp ]; } && {
	shopt -s extglob

	printf -v X "%s" "$(/usr/bin/mocp --format="%file")"
	printf -v X "%s" "${X//*\/}"
	printf -v X "%s" "${X%.+([0-9A-Za-z])}"

	/usr/bin/notify-send  "$X"
}
