#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - $HOME/.i3a/use_dmenu
# Started On        - Sat 23 Sep 14:47:51 BST 2017
# Last Change       - Mon 23 Oct 01:43:28 BST 2017
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

[ $UID -eq 0 ] && exit 1

[ -x /usr/bin/dmenu_run ] && {
	/usr/bin/dmenu_run -p "Execute:" -fn Oxygen-Mono:style=Bold:size=13 -b\
		-nb \#000000 -nf \#ffffff -sb \#333333 -sf \#ffffff
}
