#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - $HOME/.i3a/use_dmenu
# Started On        - Sat 23 Sep 14:47:51 BST 2017
# Last Change       - Sun 24 Sep 01:13:44 BST 2017
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

[ $UID -eq 0 ] && exit 1

if type -P /usr/bin/dmenu_run &> /dev/null
then
	/usr/bin/dmenu_run -fn FreeMono:style=Bold:size=12 -b\
		-nb \#000000 -nf \#ffffff -sb \#333333 -sf \#ffffff
fi
